# Use a imagem do nginx como base
FROM nginx:alpine

# Copie os arquivos do front-end para o diretório padrão do nginx
COPY index.html /usr/share/nginx/html/

# Exponha a porta 80 para acessar o front-end
EXPOSE 80

# Defina o comando padrão para iniciar o nginx
CMD ["nginx", "-g", "daemon off;"]
